export const PRODUCT_FAILURE = "PRODUCT_FAILURE";
export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const ADD_SHIPPING_SUCCESS = "ADD_SHIPPING_SUCCESS";
export const GET_SHIPPING_SUCCESS = "GET_SHIPPING_SUCCESS";
export const ADD_CART2_SUCCESS = "ADD_CART2_SUCCESS";
export const GET_CART2_SUCCESS = "GET_CART2_SUCCESS";
